environment:
  nuget_version: 0.3.1

platform: Any CPU
configuration: Release

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: false

assembly_info:
  patch: true
  file: src\AssemblyInfo.Common.cs
  assembly_version: '$(nuget_version)'
  assembly_file_version: '$(nuget_version)'
  assembly_informational_version: '$(APPVEYOR_REPO_COMMIT)'

before_build:
 - nuget restore .\src\Esp.Net.sln
  
build:
  project: src\Esp.Net.sln
  verbosity: detailed

after_build:
  - cmd: nuget pack .\src\Esp.Net\Esp.Net.nuspec -version "%nuget_version%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack .\src\Esp.Net\Esp.Net.nuspec -version "%nuget_version%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: nuget pack .\src\Esp.Net\Esp.Net.SourcePackage.nuspec -version "%nuget_version%"
  - cmd: nuget pack .\src\Esp.Net.Workflow\Esp.Net.Workflow.nuspec -version "%nuget_version%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack .\src\Esp.Net.Workflow\Esp.Net.Workflow.nuspec -version "%nuget_version%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: nuget pack .\src\Esp.Net.Workflow\Esp.Net.Workflow.SourcePackage.nuspec -version "%nuget_version%"  
  - cmd: nuget pack .\src\Esp.Net.Dispatchers\Esp.Net.Dispatchers.nuspec -version "%nuget_version%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack .\src\Esp.Net.Dispatchers\Esp.Net.Dispatchers.nuspec -version "%nuget_version%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: nuget pack .\src\Esp.Net.Dispatchers\Esp.Net.Dispatchers.SourcePackage.nuspec -version "%nuget_version%"  

artifacts:
- path: '*.nupkg'