assembly_info:
  patch: false

platform: Any CPU
configuration: Release

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: false

before_build:
 - .\tools\nuget.exe restore .\src\Esp.Net.sln
 - ps: ./tools/gitversion.exe /l console /output buildserver /updateAssemblyInfo
  
build:
  project: src\Esp.Net.sln
  verbosity: detailed

after_build:
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net\Esp.Net.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net\Esp.Net.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net\Esp.Net.SourcePackage.nuspec -version "%GitVersion_NuGetVersion%"
  
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net.Workflow\Esp.Net.Workflow.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net.Workflow\Esp.Net.Workflow.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net.Workflow\Esp.Net.Workflow.SourcePackage.nuspec -version "%GitVersion_NuGetVersion%"  
  
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net.Dispatchers\Esp.Net.Dispatchers.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net.Dispatchers\Esp.Net.Dispatchers.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: .\tools\nuget.exe pack .\src\Esp.Net.Dispatchers\Esp.Net.Dispatchers.SourcePackage.nuspec -version "%GitVersion_NuGetVersion%"  

  - cmd: appveyor PushArtifact "esp-net.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "esp-net.%GitVersion_NuGetVersion%.symbols.nupkg"
  - cmd: appveyor PushArtifact "esp-net-source.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "esp-net-workflow.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "esp-net-workflow.%GitVersion_NuGetVersion%.symbols.nupkg"
  - cmd: appveyor PushArtifact "esp-net-workflow-source.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "esp-net-dispatchers.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "esp-net-dispatchers.%GitVersion_NuGetVersion%.symbols.nupkg"
  - cmd: appveyor PushArtifact "esp-net-dispatchers-source.%GitVersion_NuGetVersion%.nupkg"